USE [Northwind]
GO

/****** Object:  Table [dbo].[BANK_ACCOUNT]    Script Date: 23.05.2022 19:46:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BANK_ACCOUNT](
	[ACCOUNT_ID] [int] NOT NULL,
	[NEXT_CAPITALIZATION_DATE] [date] NOT NULL,
	[NUMBER_OF_HOLDERS] [int] NOT NULL,
	[INTEREST_RATE] [float] NOT NULL,
	[BALANCE] [money] NOT NULL,
 CONSTRAINT [PK_BANK_ACCOUNT] PRIMARY KEY CLUSTERED 
(
	[ACCOUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


